# Colors (Pencil Dark)

[general]
import = [
    "~/.config/alacritty/themes/themes/pencil_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
opacity = 1.0
padding = { x = 0 }
decorations = "None"

[cursor]
style = { 'shape' = 'Beam', 'blinking' = 'Off' }
