# Colors (Pencil Dark)

# Default Colors
[colors.primary]
background = '#212121'
foreground = '#f1f1f1'

# Normal colors
[colors.normal]
black   = '#212121'
red     = '#c30771'
green   = '#10a778'
yellow  = '#a89c14'
blue    = '#008ec4'
magenta = '#523c79'
cyan    = '#20a5ba'
white   = '#e0e0e0'

# Bright colors
[colors.bright]
black   = '#818181'
red     = '#fb007a'
green   = '#5fd7af'
yellow  = '#f3e430'
blue    = '#20bbfc'
magenta = '#6855de'
cyan    = '#4fb8cc'
white   = '#f1f1f1'

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Control|Shift"

[scrolling]
history = 10000

[window]
opacity = 1.0
padding = { x = 0 }
decorations = "None"

[cursor]
style = { 'shape' = 'Beam', 'blinking' = 'Off' }
